# GitHub on Hacker News trends analysis

In [11]:
!pip install pandas pandas-gbq

!pip install --upgrade pyarrow

Requirement already satisfied: pandas in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (2.0.3)
Requirement already satisfied: pandas-gbq in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (0.23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.25.2)
Requirement already satisfied: setuptools in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (65.5.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: pyarrow>=3.0.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (17.0.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (1.8.2)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (2.20.0)
Requirement already satisfied: google-auth>=2.13.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (2.35.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (1.2.1)
Requirement already satisfied: google-cloud-bigquery<4.0.0dev,>=3.4.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (3.25.0)
Requirement already satisfied: packaging>=22.0.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pandas-gbq) (23.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.65.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (5.28.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.24.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-bigquery<4.0.0dev,>=3.4.2->pandas-gbq) (2.4.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-bigquery<4.0.0dev,>=3.4.2->pandas-gbq) (2.7.2)
Requirement already satisfied: six>=1.5 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.66.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.66.1)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<4.0.0dev,>=3.4.2->pandas-gbq) (1.6.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2023.7.22)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.2)

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (17.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\poste\appdata\local\programs\python\python311\lib\site-packages (from pyarrow) (1.25.2)

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
from __future__ import print_function
import pandas as pd
import pyarrow as pa

In [6]:
project_id = "the-axiom-436718-r3"
process_date = "2018-12-01"
process_date_nodash = "20181201"

## Exploratory Data Analysis

## Github activity data
- Link: [Data](https://bigquery.cloud.google.com/table/githubarchive:day.20181230) - [More info](https://blog.github.com/2017-01-19-github-data-ready-for-you-to-explore-with-bigquery/)

## EVENT TYPES

In [7]:
query = """
SELECT 
  type,
  COUNT(*) AS cnt
FROM `githubarchive.day.{0}` 
GROUP BY 1
ORDER BY 2 DESC
""".format(process_date_nodash)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  type,
  COUNT(*) AS cnt
FROM `githubarchive.day.20181201`
GROUP BY 1
ORDER BY 2 DESC

                             type     cnt
0                       PushEvent  588724
1                     CreateEvent  155010
2                      WatchEvent   67607
3                PullRequestEvent   56635
4               IssueCommentEvent   46972
5                     IssuesEvent   27592
6                       ForkEvent   24331
7                     DeleteEvent   22590
8   PullRequestReviewCommentEvent    9756
9                     MemberEvent    5201
10                    GollumEvent    4445
11                   ReleaseEvent    3527
12             CommitCommentEvent    1759
13                    PublicEvent    1064

### Top 10 repos with the most comments in their issues

In [8]:
query = """
SELECT 
  repo.name,
  COUNT(*) AS cnt
FROM `githubarchive.day.{0}`
WHERE type IN ( 'IssueCommentEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
""".format(process_date_nodash)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  repo.name,
  COUNT(*) AS cnt
FROM `githubarchive.day.20181201`
WHERE type IN ( 'IssueCommentEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

                                   name  cnt
0        google-test/signcla-probe-repo  327
1            Azure/azure-rest-api-specs  287
2                 kubernetes/kubernetes  227
3                        rust-lang/rust  207
4                          apache/spark  204
5             freeCodeCamp/freeCodeCamp  196
6  everypolitician/everypolitician-data  192
7                   TeamNewPipe/NewPipe  158
8                      openshift/origin  140
9                         NixOS/nixpkgs  126

### Top 10 repos by stars and fork event

In [9]:
query = """
SELECT 
  repo.name,
  SUM(IF(type='WatchEvent', 1, NULL)) AS stars,
  SUM(IF(type='ForkEvent',  1, NULL)) AS forks,
  COUNT(*) AS cnt
FROM `githubarchive.day.{0}`
WHERE type IN ('WatchEvent','ForkEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
""".format(process_date_nodash)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  repo.name,
  SUM(IF(type='WatchEvent', 1, NULL)) AS stars,
  SUM(IF(type='ForkEvent',  1, NULL)) AS forks,
  COUNT(*) AS cnt
FROM `githubarchive.day.20181201`
WHERE type IN ('WatchEvent','ForkEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

                                        name  stars  forks  cnt
0                            BcRikko/NES.css    386     35  421
1                  leisurelicht/wtfpython-cn    241     31  272
2                     satwikkansal/wtfpython    190     30  220
3             cssanimation/css-animation-101    178      5  183
4            firecracker-microvm/firecracker    150     13  163
5            crazyandcoder/kindle_free_books    132     31  163
6                      withspectrum/spectrum    132      9  141
7     afshinea/stanford-cs-230-deep-learning    120     17  137
8  algorithm-visualizer/algorithm-visualizer    119     15  134
9                       olifolkerd/tabulator    114      3  117

### Top Actors Commenting on Issues

In [19]:
query = """
SELECT 
  actor.login,
  COUNT(*) AS cnt
FROM `githubarchive.day.{0}`
WHERE type IN ('IssueCommentEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
""".format('20240902')

print(query)
df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  actor.login,
  COUNT(*) AS cnt
FROM `githubarchive.day.20240902`
WHERE type IN ('IssueCommentEvent')
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

                   login    cnt
0        dependabot[bot]  33037
1    github-actions[bot]  19010
2            vercel[bot]   9911
3        sonarcloud[bot]   8642
4     plutointegtestuser   4262
5           codecov[bot]   3447
6           netlify[bot]   3320
7      coderabbitai[bot]   2182
8      openshift-ci[bot]   1963
9  cloudflare-pages[bot]   1432

## Hacker News data
- Link: [Data](https://bigquery.cloud.google.com/table/bigquery-public-data:hacker_news.full) - [More info](https://medium.com/@hoffa/hacker-news-on-bigquery-now-with-daily-updates-so-what-are-the-top-domains-963d3c68b2e2)

### Top domains shared in Hacker News

In [10]:
query = """
SELECT 
  REGEXP_EXTRACT(url, '//([^/]*)/?') as domain,
  AVG(score) as avg_score,
  COUNT(*) AS cnt
FROM `bigquery-public-data.hacker_news.full`
WHERE url!='' 
AND EXTRACT(DATE FROM timestamp)="{0}"
GROUP BY 1
ORDER BY 3 DESC 
LIMIT 10
""".format(process_date)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  REGEXP_EXTRACT(url, '//([^/]*)/?') as domain,
  AVG(score) as avg_score,
  COUNT(*) AS cnt
FROM `bigquery-public-data.hacker_news.full`
WHERE url!=''
AND EXTRACT(DATE FROM timestamp)="2018-12-01"
GROUP BY 1
ORDER BY 3 DESC
LIMIT 10

                domain  avg_score  cnt
0           github.com  14.966667   30
1           medium.com  15.592593   27
2      www.youtube.com  12.666667   24
3      www.nytimes.com  41.263158   19
4      venturebeat.com   2.100000   10
5       www.reddit.com  21.428571    7
6      arstechnica.com  22.666667    6
7     en.wikipedia.org  15.833333    6
8  www.theguardian.com  31.166667    6
9     www.theverge.com   2.200000    5

### What domains have the best chance of getting more than 40 upvotes?

In [11]:
query = """
SELECT 
  REGEXP_EXTRACT(url, '//([^/]*)/?') as domain,
  COUNTIF(score>40) as score_gt_40,
  COUNT(*) AS cnt
FROM `bigquery-public-data.hacker_news.full`
WHERE url!='' 
AND EXTRACT(DATE FROM timestamp)="{0}"
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 10
""".format(process_date)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(20)

SELECT
  REGEXP_EXTRACT(url, '//([^/]*)/?') as domain,
  COUNTIF(score>40) as score_gt_40,
  COUNT(*) AS cnt
FROM `bigquery-public-data.hacker_news.full`
WHERE url!=''
AND EXTRACT(DATE FROM timestamp)="2018-12-01"
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

                domain  score_gt_40  cnt
0      www.nytimes.com            4   19
1           github.com            4   30
2           medium.com            3   27
3  www.theatlantic.com            2    5
4          www.wsj.com            2    4
5      www.youtube.com            2   24
6       redditblog.com            1    1
7  www.newsshooter.com            1    1
8        jeremykun.com            1    1
9        www.zdnet.com            1    3

### Top 10 Hacker news stories from Github by highest score

In [12]:
query = """
SELECT     
  `by` AS submitter,
  id as story_id,
  REGEXP_EXTRACT(url, "(https?://github.com/[^/]*/[^/#?]*)") as url,
  SUM(score) as score
FROM
  `bigquery-public-data.hacker_news.full`
WHERE
  type = 'story'
  AND EXTRACT(DATE FROM timestamp)='{0}' 
  AND url LIKE '%https://github.com%'
  AND url NOT LIKE '%github.com/blog/%'
GROUP BY  
  submitter,
  story_id,
  url
ORDER BY score DESC
""".format(process_date)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(10)

SELECT
  `by` AS submitter,
  id as story_id,
  REGEXP_EXTRACT(url, "(https?://github.com/[^/]*/[^/#?]*)") as url,
  SUM(score) as score
FROM
  `bigquery-public-data.hacker_news.full`
WHERE
  type = 'story'
  AND EXTRACT(DATE FROM timestamp)='2018-12-01'
  AND url LIKE '%https://github.com%'
  AND url NOT LIKE '%github.com/blog/%'
GROUP BY
  submitter,
  story_id,
  url
ORDER BY score DESC

,submitter,story_id,url,score
0,ithinco,18574181,https://github.com/ithinco/i-am-chinese-the-dr...,129
1,mountainview,18576170,https://github.com/YugaByte/yugabyte-db,115
2,oxplot,18575094,https://github.com/oxplot/pdftilecut,64
3,codeadict,18574683,https://github.com/alertlogic/erllambda,64
4,pjmlp,18575802,https://github.com/chocolatey/boxstarter,9
5,snek,18577658,https://github.com/devsnek/engine262,8
6,andrewchaa,18574107,https://github.com/andrewchaa/functional.pipe,4
7,anmonteiro90,18578964,https://github.com/anmonteiro/aws-lambda-ocaml...,4
8,delvincasper,18577036,https://github.com/jerverless/jerverless,4
9,KumarAbhirup,18577887,https://github.com/KumarAbhirup/bulk-mail-cli,4

## Example Final table: GitHub on Hacker News Trends of 2018-12-01

In [13]:
query = """
WITH github_activity AS (
SELECT   
  repo.name as repo,
  CONCAT('https://github.com/', repo.name) as url,
  SUM(IF(type='WatchEvent', 1, NULL)) AS stars,
  SUM(IF(type='ForkEvent',  1, NULL)) AS forks,
  COUNT(*) AS cnt
FROM `githubarchive.day.{0}`
WHERE type IN ('WatchEvent','ForkEvent')
GROUP BY 1,2
),
hacker_news AS (
SELECT
  EXTRACT(DATE FROM timestamp) as date,
  `by` AS submitter,
  id as story_id,
  REGEXP_EXTRACT(url, "(https?://github.com/[^/]*/[^/#?]*)") as url,
  SUM(score) as score
FROM
  `bigquery-public-data.hacker_news.full`
WHERE
  type = 'story'
  AND EXTRACT(DATE FROM timestamp)='{1}' 
  AND url LIKE '%https://github.com%'
  AND url NOT LIKE '%github.com/blog/%'
GROUP BY 1,2,3,4
)

SELECT
  a.date as date,
  a.url as github_url,
  b.repo as github_repo,
  a.score as hn_score,
  a.story_id as hn_story_id,
  b.stars as stars,
  b.forks as forks
FROM hacker_news as a
LEFT JOIN github_activity as b
ON a.url=b.url
ORDER BY hn_score DESC
LIMIT 10
""".format(process_date_nodash, process_date)

print (query)

df = pd.read_gbq(query, project_id=project_id, dialect='standard')
df.head(10)

WITH github_activity AS (
SELECT
  repo.name as repo,
  CONCAT('https://github.com/', repo.name) as url,
  SUM(IF(type='WatchEvent', 1, NULL)) AS stars,
  SUM(IF(type='ForkEvent',  1, NULL)) AS forks,
  COUNT(*) AS cnt
FROM `githubarchive.day.20181201`
WHERE type IN ('WatchEvent','ForkEvent')
GROUP BY 1,2
),
hacker_news AS (
SELECT
  EXTRACT(DATE FROM timestamp) as date,
  `by` AS submitter,
  id as story_id,
  REGEXP_EXTRACT(url, "(https?://github.com/[^/]*/[^/#?]*)") as url,
  SUM(score) as score
FROM
  `bigquery-public-data.hacker_news.full`
WHERE
  type = 'story'
  AND EXTRACT(DATE FROM timestamp)='2018-12-01'
  AND url LIKE '%https://github.com%'
  AND url NOT LIKE '%github.com/blog/%'
GROUP BY 1,2,3,4
)

SELECT
  a.date as date,
  a.url as github_url,
  b.repo as github_repo,
  a.score as hn_score,
  a.story_id as hn_story_id,
  b.stars as stars,
  b.forks as forks
FROM hacker_news as a
LEFT JOIN github_activity as b
ON a.url=b.url
ORDER BY hn_score DESC
LIMIT 10

,date,github_url,github_repo,hn_score,hn_story_id,stars,forks
0,2018-12-01,https://github.com/ithinco/i-am-chinese-the-dr...,ithinco/i-am-chinese-the-dragonfly-must-go-on,129,18574181,60,1
1,2018-12-01,https://github.com/YugaByte/yugabyte-db,YugaByte/yugabyte-db,115,18576170,2,<NA>
2,2018-12-01,https://github.com/oxplot/pdftilecut,oxplot/pdftilecut,64,18575094,91,<NA>
3,2018-12-01,https://github.com/alertlogic/erllambda,alertlogic/erllambda,64,18574683,48,<NA>
4,2018-12-01,https://github.com/chocolatey/boxstarter,chocolatey/boxstarter,9,18575802,1,<NA>
5,2018-12-01,https://github.com/devsnek/engine262,devsnek/engine262,8,18577658,1,<NA>
6,2018-12-01,https://github.com/KumarAbhirup/bulk-mail-cli,None,4,18577887,<NA>,<NA>
7,2018-12-01,https://github.com/andrewchaa/functional.pipe,andrewchaa/functional.pipe,4,18574107,2,<NA>
8,2018-12-01,https://github.com/jerverless/jerverless,None,4,18577036,<NA>,<NA>
9,2018-12-01,https://github.com/anmonteiro/aws-lambda-ocaml...,anmonteiro/aws-lambda-ocaml-runtime,4,18578964,5,<NA>